In [9]:
import pandas as pd 

df_movies = pd.DataFrame({
    '연평해전':[5,5,4], 
    '7번방의 선물':[4,3,3], 
    '국제시장':[4,4,3], 
    '명랑':['',5,3], 
    '국가대표':['',3,5]
})
df_movies.index=['user1', 'user2', 'user3']
df_movies

       연평해전  7번방의 선물  국제시장 명랑 국가대표
user1     5        4     4
user2     5        3     4  5    3
user3     4        3     3  3    5

In [11]:
import pandas as pd 

movies = [
  ['user1', '연평대전', 5],
  ['user1', '7번방의 선물', 4],
  ['user1', '국제시장', 4],
  ['user2', '연평대전', 5],
  ['user2', '7번방의 선물', 3],
  ['user2', '국제시장', 4],
  ['user2', '명랑', 5],
  ['user2', '국가대표', 3],
  ['user2', '연평대전', 4],
  ['user2', '7번방의 선물', 3],
  ['user2', '국제시장', 3],
  ['user2', '명랑', 3],
  ['user2', '국가대표', 5]
]
df_movies = pd.DataFrame(movies, columns=['userID', 'movieName', 'Rating'])
df_movies

   userID movieName  Rating
0   user1      연평대전       5
1   user1   7번방의 선물       4
2   user1      국제시장       4
3   user2      연평대전       5
4   user2   7번방의 선물       3
5   user2      국제시장       4
6   user2        명랑       5
7   user2      국가대표       3
8   user2      연평대전       4
9   user2   7번방의 선물       3
10  user2      국제시장       3
11  user2        명랑       3
12  user2      국가대표       5