#Quiz
위의 내용에서 발생되는 결측치를 평균으로 치환하시오

## 풀이

###힌트1

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/1. 데이터 분석을 위한 기초 통계 수학/1. 데이터 클랜징/data/bicycle.csv', engine='python', encoding='cp949')
df

>위의 내용에서 이용거리별 이용시간이 나올듯 하지만 이용 거리와 관계 없이 이용시간이 나타나는 것을 알 수 있다. 예를 들어 1100미터를 이동하는데 12분이 걸린 반면 1420미터를 이동하는데 7분이 소요되었다. 거리는 늘었지만 시간이 준 경우이기 때문에 이를 이용하여 이용시간을 지정할 수는 없다.

In [ ]:
df[df['대여소번호']==646]

>결측치 치환은 누락되거나 비어 있는 데이터를 임의의 데이터로 변경하는 작업을 의미한다. 변경 시 기존 데이터 분석에 영향을 줄이려면 대표값을 입력해야 한다. 본 Quiz에서는 평균값 치환에 대해 알아 보려고 한다.

> 평균이란 그룹내의 대표값이 된다. 이렇게 그룹내의 평균을 알아보기 위해 그룹을 묶어 주어야 하며 같은 대여소에서 발생되는 이벤트는 비슷하게 이루어 질 것이기 때문에 위처럼 대여소 번호로 그룹을 묶어야 한다.

In [ ]:
import numpy as np

# df2 = df
# df2.replace(np.nan, 'test')

# df2 = df
# df2.replace({'이용거리':np.nan}, {'이용거리':'test'})

         자전거번호              대여일시  대여소번호  ... 반납거치대  이용시간  이용거리
0    SPB-23220   2019-11-01 8:48    646  ...   7.0  12.0  1100
1    SPB-16216   2019-11-04 8:38    646  ...   2.0   7.0  1420
2    SPB-21097   2019-11-04 8:46    646  ...   7.0  10.0  test
3    SPB-22292   2019-11-05 8:34    646  ...   NaN  10.0  1380
4    SPB-07935  2019-11-05 12:29    512  ...   7.0  10.0  1650
..         ...               ...    ...  ...   ...   ...   ...
415  SPB-12116   2019-11-15 4:22    112  ...   1.0  11.0  2200
416  SPB-17768   2019-11-15 9:31    103  ...   NaN   5.0  test
417  SPB-18841  2019-11-15 20:40    113  ...   1.0  12.0  2280
418  SPB-24467  2019-11-15 21:55    152  ...   1.0  10.0  1180
419  SPB-17570  2019-11-15 22:16    391  ...   5.0  48.0  8100

[420 rows x 11 columns]

> 이번에는 간단히 replace 사용법에 대해 알아보려 한다. replace는 첫 번째 인자를 두 번째 인자로 치환해 주는 함수이다. dataframe에 replace를 적용하면 모든 row에 적용되어 문제가 발생된다. 

> 특정 위치에만 적용하기 위해서는 주석 내용처럼 json 형식으로 값을 지정하여 변경할 수 있다.

>위의 내용을 힌트로 보여 주고 위처럼 접근할 수 있도록 코딩을 유도한다.

###힌트2

In [ ]:
import numpy as np

# df[df['대여소번호']==646]
# df[df['대여소번호']==646]['이용거리']

df2 = df

mean646 = df2[df2['대여소번호']==646]['이용거리'].mean()
df2[df2['대여소번호']==646]=df2[df2['대여소번호']==646].replace({'이용거리':np.nan}, {'이용거리':mean646})
df2

         자전거번호              대여일시  대여소번호  ... 반납거치대  이용시간    이용거리
0    SPB-23220   2019-11-01 8:48    646  ...   7.0  12.0  1100.0
1    SPB-16216   2019-11-04 8:38    646  ...   2.0   7.0  1420.0
2    SPB-21097   2019-11-04 8:46    646  ...   7.0  10.0  1256.0
3    SPB-22292   2019-11-05 8:34    646  ...   NaN  10.0  1380.0
4    SPB-07935  2019-11-05 12:29    512  ...   7.0  10.0  1650.0
..         ...               ...    ...  ...   ...   ...     ...
415  SPB-12116   2019-11-15 4:22    112  ...   1.0  11.0  2200.0
416  SPB-17768   2019-11-15 9:31    103  ...   NaN   5.0     NaN
417  SPB-18841  2019-11-15 20:40    113  ...   1.0  12.0  2280.0
418  SPB-24467  2019-11-15 21:55    152  ...   1.0  10.0  1180.0
419  SPB-17570  2019-11-15 22:16    391  ...   5.0  48.0  8100.0

[420 rows x 11 columns]

> 적당한 시간이 흐르면 위의 코드를 설명해 준다.
1. 대여소 번호별로 출력되는지 확인한다.
2. 같은 대여소 번호에서 이용거리만 출력되는지 확인한다.

>위의 확인이 끝나면 646번 대여소번호의 평균을 구하고 이를 이용거리 결측치 부분에 대입한 후 결과를 확인한다.

###힌트3
>다음과 같은 순서로 코딩할 수 있도록 유도한다.
1. 결측열 찾기
2. 대여소 번호 얻기
3. 대여소번호와 column 명을 전달하면 변경

In [ ]:
df2 = df

###힌트4

In [ ]:
# 결측 열 찾기
def getMissingList(dataFrame):
  dataSeries = dataFrame.isnull().sum()
  missingSeries = dataSeries[dataSeries>0]
  return missingSeries.index.to_list()

lst = getMissingList(df2)
for row in lst:
  print(row)

In [ ]:
# 대여소 번호 얻기
def getNoList(dataFrame):
  noSeries  = dataFrame['대여소번호'].drop_duplicates()
  return noSeries.values.tolist()

nolst = getNoList(df2)
nolst

###힌트5

In [ ]:
# 대여소번호와 column 명을 전달하면 변경
def ReplaceNaN(dataFrame, no, colName):
  mean = round(dataFrame[dataFrame['대여소번호']==no][colName].mean(),0)
  dataFrame[dataFrame['대여소번호']==no] = dataFrame[dataFrame['대여소번호']==no].replace({colName:np.nan}, {colName:mean})

  return dataFrame

df2 = ReplaceNaN(df2, 103, '반납거치대')
df2

In [ ]:
for no in nolst:
  for row in lst:
    df2 = ReplaceNaN(df2, no, row)

df2